version: '3'

services:
  php:
    build: ./docker/php
    image: stackit-php:8.0
    ports: [ "80:8080" ]
    volumes:
      - ./app:/var/www:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports: [ "9200:9200" ]
