version: '3'

services:
  php:
      build: ./docker/php
      image: base-alpine-php:7.4
      extra_hosts:
          - "host.docker.internal:host-gateway"
      volumes:
          - ./app:/var/www:cached

  nginx:
      build: ./docker/nginx
      image: base-nginx:latest
      volumes:
          - ./app:/var/www:cached
          - ./logs/nginx:/var/log/nginx:cached
      ports:
          - "80:80"
          - "443:443"
  db:
    build: ./docker/db
    image: base-db:latest
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports: [2345:5432]
    restart: always


